### ISSUE TITLE
Error In lib/cairo/lib_cairo.cr:26:14, undefined constant LibCairo::Status

### ISSUE THREAD

**Issue by gummybears** [viachpaliy/cairo-gobject#3]
Linux Mint 18.2, 64 bits

Followed the instructions 
```
$ sudo apt-get install libgirepository1.0-dev libgtk-3-dev libcairo-gobject2 gir1.2-freedesktop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-freedesktop is already the newest version (1.46.0-3ubuntu1).
libcairo-gobject2 is already the newest version (1.14.6-1).
libgirepository1.0-dev is already the newest version (1.46.0-3ubuntu1).
libgtk-3-dev is already the newest version (3.18.9-1ubuntu3.3).

```
shards.yml
```
name: test
version: 0.0.1

dependencies:
  gobject:
    github: jhass/crystal-gobject
    version: ~> 0.8.0

  cairo-gobject:
    github: viachpaliy/cairo-gobject
```
```
cd cairo-gobject
  shards install
  crystal run samples/gtk_sample.cr
```
I got the following error
```
Showing last frame. Use --error-trace for full trace.

In lib/cairo/lib_cairo.cr:26:14

 26 | status : LibCairo::Status
               ^---------------
Error: undefined constant LibCairo::Status
```
